[package]
name = "rolling-timestamp"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin_hashes = "0.18.0"
breccia = { path = "../breccia" }
thiserror = "2.0.17"
opentimestamps = { path = "../rust-opentimestamps" }

[dev-dependencies]
tempfile = "3.23.0"
